[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#22272E"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#537188"

# Color used for almost all text.
textColor = "#fff" 